var imgs = {
	play: './assets/images/play.png',
	logo: './assets/images/logo.png',
	ar: './assets/images/ar.png',
	arrow: './assets/images/arrow.png',
	yun: './assets/images/yun.png',
	part1: './assets/images/4-1.png',
	part2: './assets/images/4-2.png',
	part3: './assets/images/4-3.png',
	part4: './assets/images/4-4.png',
	part5: './assets/images/4-5.png',
	part6: './assets/images/4-6.png',
	dream1: './assets/images/6-1.png',
	dream2: './assets/images/6-2.png',

	img1: './assets/images/1.jpg',
	img2: './assets/images/2.jpg',
	img3: './assets/images/3.jpg',
	img4: './assets/images/4.jpg',
	img5: './assets/images/5.jpg',
	img6: './assets/images/6.jpg',
	img7: './assets/images/7.jpg',
	img8: './assets/images/8.jpg',
	img9: './assets/images/9.jpg',

	letter: './assets/images/5-1.png',
	sign2017: './assets/images/7-1.png',

	map: './assets/images/map.png',
	pagenum: './assets/images/pagenum.png',
	pagenum1: './assets/images/pagenum1.png',
	indexBg: './assets/images/index-bg.jpg',
	kpy: './assets/images/kpy.jpg',
	house: './assets/images/index-hourse.png',
	indexText: './assets/images/index-text.png',
	pageimg1: './assets/images/1.png',
};
export default imgs;